spring:
  datasource:
    url: jdbc:mysql://192.168.8.213:3306/test?characterEncoding=UTF-8&useSSL=false
    username: root
    password: qaz123456.
  kafka:
    consumer:
      group-id: test4
      enableAutoCommit: true
      bootstrap-servers: 192.168.8.83:9092
      auto-offset-reset: latest
    producer:
      bootstrap-servers: 192.168.8.83:9092
  redis:
    host: localhost
    port: 6379
kafka:
  canal:
    topic: test-canal
mybatis:
  mapper-locations: classpath:mapperxml/*.xml